### ISSUE TITLE
Missing libcurl-gnutls.so.4 on Fedora

### ISSUE THREAD

**Issue by cdelg** [RPM-Outpost/gitkraken#3]
When I try to install the package on Fedora 28 built with the script I get this error:

> Error: 
> Problem: conflicting requests
> - nothing provides libcurl-gnutls.so.4()(64bit) needed by gitkraken-3.6.1-2.fc28.x86_64 

Do you know how to solve it?

**Comment by ivanruvalcaba** [comment]
@cdelg Install the package (_root_) with: `rpm -i --nodeps`.

If you can't run the app, exec from de terminal:

```sh
sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4
```

_source:_ https://support.gitkraken.com/how-to-install

**Offtipic:**

**Gitkraken >= 3.6** does not work for me, though (is unable to clone from Github nor GitLab and working from my local repositories the application reloads the interface infinitely).

_My system:_ Fedora 28 (x64), Gnome, fresh install, up-to-date.

My dirty fix was to install **Gitkraken 3.5.1**, I get it from here: http://download.opensuse.org/repositories/home:/gallochri/openSUSE_Tumbleweed/src/gitkraken-3.5.1-2.1.src.rpm. Then, unzip the package, create the `work` directory and put up the `gitkraken-amd64.tar.gz` file in there. Rename this file as `gitkraken-linux.tar.gz` and finally run the script normally.

Does anyone know how to fix this? :-/

@TheElectronWill AFAIK, Maybe you should update the following line in the `gitkraken.spec` file:

```sh
Release:	2%{?dist}
```
by:

```sh
Release:	1%{?dist}
```

Anyway, thanks for sharing!

Best regards.

**Comment by cdelg** [comment]
Ok thanks, I have the same issue (UI reload) that's why I tried with this script, but without success...

**Comment by TheElectronWill** [comment]
Ah, looks like the symlink I've used for libcurl-gnutls.so.4 doesn't work anymore :/
UI problems in 3.6 might be caused by a missing or wrong dependency in my spec.
I'll investigate this issue soon. Thanks for reporting!

**Comment by ivanruvalcaba** [comment]
Gitkraken >= 3.6 added check spelling functionality (possible hint). En Manjaro (Arch Linux derivated) worked fine AFAIK, maybe you can take a look in your "spec's" files:

+ https://aur.archlinux.org/packages/gitkraken/
+ https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gitkraken

I'd love to help but I'm really busy right now.

Best regards.

**Comment by cdelg** [comment]
@ivanruvalcaba are you using a security key or gpg-agent ?

**Comment by ivanruvalcaba** [comment]
@cdelg ssh-agent

**Comment by TheElectronWill** [comment]
Even with the manual link to libcurl, dnf complains about the missing library :-/

**Comment by mgdodge** [comment]
I too am having the UI reload issue. I have the libcurl symlink in place.

Have noticed that when I am offline, I can open repos just fine and the ui doesn't reload. Once I get back online, trying to fetch from remote will start the UI reload issue again.

I'm not as well versed in linux as I would like, so I am not sure where to go from here. Maybe this info will help someone get one step closer to a solution.

**Comment by ivanruvalcaba** [comment]
Maybe anybody can take a look to the flatpack package and try to find clues
at this situation:

https://flathub.org/apps/details/com.axosoft.GitKraken

If you want to install it from there then you can following the steps to
get up and running:

https://fedoramagazine.org/install-flathub-apps-fedora/

Works like a charm for me.

Best regards.


El jul. 24, 2018 1:53, "mgdodge" <notifications@github.com> escribió:

I too am having the UI reload issue. I have the libcurl symlink in place.

Have noticed that when I am offline, I can open repos just fine and the ui
doesn't reload. Once I get back online, trying to fetch from remote will
start the UI reload issue again.

I'm not as well versed in linux as I would like, so I am not sure where to
go from here. Maybe this info will help someone get one step closer to a
solution.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RPM-Outpost/gitkraken/issues/3#issuecomment-407301067>,
or mute the thread
